apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/abaas-madscience/argo-cnpg-deployment.git"
    targetRevision: HEAD
    path: k8s/cnpg-cluster # The folder containing the files below
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnpg-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
